INSERT INTO "alerts" VALUES(9601,'payments','error_rate_pct','high','firing','payments error_rate_pct 4.2 exceeds SLO 1.0');
INSERT INTO "alerts" VALUES(9602,'search','latency_p99_ms','medium','firing','search latency_p99_ms 850.0 exceeds SLO 300.0');
INSERT INTO "alerts" VALUES(9603,'checkout','error_rate_pct','high','firing','checkout error_rate_pct 5.5 exceeds SLO 1.0');
INSERT INTO "alerts" VALUES(9604,'api-gateway','latency_p99_ms','critical','firing','api-gateway latency_p99_ms 1030.0 exceeds SLO 250.0');
INSERT INTO "audit_events" VALUES(1,'deploy_service','storefront-web','{"environment": "staging", "version": "v3.2.4", "canary_percent": 100, "applied": true}');
INSERT INTO "audit_events" VALUES(2,'deploy_service','storefront-web','{"environment": "production", "version": "v3.2.4", "canary_percent": 100, "applied": true}');
INSERT INTO "audit_events" VALUES(3,'deploy_service','api-gateway','{"environment": "staging", "version": "v5.0.9", "canary_percent": 100, "applied": true}');
INSERT INTO "audit_events" VALUES(4,'deploy_service','api-gateway','{"environment": "production", "version": "v5.0.9", "canary_percent": 100, "applied": true}');
INSERT INTO "audit_events" VALUES(5,'deploy_service','catalog','{"environment": "staging", "version": "v1.9.2", "canary_percent": 100, "applied": true}');
INSERT INTO "audit_events" VALUES(6,'deploy_service','catalog','{"environment": "production", "version": "v1.9.2", "canary_percent": 100, "applied": true}');
INSERT INTO "audit_events" VALUES(7,'deploy_service','checkout','{"environment": "staging", "version": "v2.6.3", "canary_percent": 100, "applied": true}');
INSERT INTO "audit_events" VALUES(8,'deploy_service','checkout','{"environment": "production", "version": "v2.6.3", "canary_percent": 100, "applied": true}');
INSERT INTO "audit_events" VALUES(9,'deploy_service','payments','{"environment": "staging", "version": "v2.7.0", "canary_percent": 100, "applied": true}');
INSERT INTO "audit_events" VALUES(10,'deploy_service','payments','{"environment": "production", "version": "v2.7.0", "canary_percent": 100, "applied": true}');
INSERT INTO "audit_events" VALUES(11,'deploy_service','notifications','{"environment": "staging", "version": "v1.4.8", "canary_percent": 100, "applied": true}');
INSERT INTO "audit_events" VALUES(12,'deploy_service','notifications','{"environment": "production", "version": "v1.4.8", "canary_percent": 100, "applied": true}');
INSERT INTO "audit_events" VALUES(13,'deploy_service','search','{"environment": "staging", "version": "v3.0.5", "canary_percent": 100, "applied": true}');
INSERT INTO "audit_events" VALUES(14,'deploy_service','search','{"environment": "production", "version": "v3.0.5", "canary_percent": 100, "applied": true}');
INSERT INTO "audit_events" VALUES(15,'deploy_service','api-gateway','{"environment": "staging", "version": "v5.1.0", "canary_percent": 100, "applied": true}');
INSERT INTO "audit_events" VALUES(16,'deploy_service','api-gateway','{"environment": "production", "version": "v5.1.0", "canary_percent": 25, "applied": false}');
INSERT INTO "audit_events" VALUES(17,'promote_canary','api-gateway','{"environment": "production", "version": "v5.1.0", "deployment_id": 9266}');
INSERT INTO "channels" VALUES('#incidents','Incident coordination and status updates.');
INSERT INTO "channels" VALUES('#security','Security advisories and audit notes.');
INSERT INTO "channels" VALUES('#eng','General engineering.');
INSERT INTO "ci_runs" VALUES(1,'api-gateway',9201,'passed','all checks passed');
INSERT INTO "ci_runs" VALUES(2,'checkout',NULL,'failed','intermittent failure: test_checkout_idempotency (rerun may pass)');
INSERT INTO "ci_runs" VALUES(3,'checkout',NULL,'passed','all checks passed');
INSERT INTO "ci_runs" VALUES(4,'payments',NULL,'passed','all checks passed');
INSERT INTO "deployments" VALUES(9251,'storefront-web','staging','v3.2.4','succeeded',100);
INSERT INTO "deployments" VALUES(9252,'storefront-web','production','v3.2.4','succeeded',100);
INSERT INTO "deployments" VALUES(9253,'api-gateway','staging','v5.0.9','succeeded',100);
INSERT INTO "deployments" VALUES(9254,'api-gateway','production','v5.0.9','succeeded',100);
INSERT INTO "deployments" VALUES(9255,'catalog','staging','v1.9.2','succeeded',100);
INSERT INTO "deployments" VALUES(9256,'catalog','production','v1.9.2','succeeded',100);
INSERT INTO "deployments" VALUES(9257,'checkout','staging','v2.6.3','succeeded',100);
INSERT INTO "deployments" VALUES(9258,'checkout','production','v2.6.3','succeeded',100);
INSERT INTO "deployments" VALUES(9259,'payments','staging','v2.7.0','succeeded',100);
INSERT INTO "deployments" VALUES(9260,'payments','production','v2.7.0','succeeded',100);
INSERT INTO "deployments" VALUES(9261,'notifications','staging','v1.4.8','succeeded',100);
INSERT INTO "deployments" VALUES(9262,'notifications','production','v1.4.8','succeeded',100);
INSERT INTO "deployments" VALUES(9263,'search','staging','v3.0.5','succeeded',100);
INSERT INTO "deployments" VALUES(9264,'search','production','v3.0.5','succeeded',100);
INSERT INTO "deployments" VALUES(9265,'api-gateway','staging','v5.1.0','succeeded',100);
INSERT INTO "deployments" VALUES(9266,'api-gateway','production','v5.1.0','succeeded',100);
INSERT INTO "env_state" VALUES('storefront-web','staging','config','ab_test_bucket','b');
INSERT INTO "env_state" VALUES('storefront-web','production','config','ab_test_bucket','b');
INSERT INTO "env_state" VALUES('storefront-web','staging','module','homepage','present');
INSERT INTO "env_state" VALUES('storefront-web','production','module','homepage','present');
INSERT INTO "env_state" VALUES('storefront-web','staging','module','product_page','present');
INSERT INTO "env_state" VALUES('storefront-web','production','module','product_page','present');
INSERT INTO "env_state" VALUES('api-gateway','staging','config','rate_limit_rps','500');
INSERT INTO "env_state" VALUES('api-gateway','production','config','rate_limit_rps','500');
INSERT INTO "env_state" VALUES('api-gateway','staging','endpoint','/v1/orders','active');
INSERT INTO "env_state" VALUES('api-gateway','production','endpoint','/v1/orders','active');
INSERT INTO "env_state" VALUES('api-gateway','staging','endpoint','/v2/orders','active');
INSERT INTO "env_state" VALUES('api-gateway','production','endpoint','/v2/orders','active');
INSERT INTO "env_state" VALUES('api-gateway','staging','endpoint','/v1/checkout','active');
INSERT INTO "env_state" VALUES('api-gateway','production','endpoint','/v1/checkout','active');
INSERT INTO "env_state" VALUES('api-gateway','staging','endpoint','/internal/debug','active');
INSERT INTO "env_state" VALUES('api-gateway','production','endpoint','/internal/debug','active');
INSERT INTO "env_state" VALUES('catalog','staging','config','cdn_enabled','true');
INSERT INTO "env_state" VALUES('catalog','production','config','cdn_enabled','true');
INSERT INTO "env_state" VALUES('catalog','staging','module','product_listing','present');
INSERT INTO "env_state" VALUES('catalog','production','module','product_listing','present');
INSERT INTO "env_state" VALUES('checkout','staging','config','payment_timeout_ms','8000');
INSERT INTO "env_state" VALUES('checkout','production','config','payment_timeout_ms','8000');
INSERT INTO "env_state" VALUES('checkout','staging','dependency','stripe-sdk','11.2.0');
INSERT INTO "env_state" VALUES('checkout','production','dependency','stripe-sdk','11.2.0');
INSERT INTO "env_state" VALUES('checkout','staging','module','cart','present');
INSERT INTO "env_state" VALUES('checkout','production','module','cart','present');
INSERT INTO "env_state" VALUES('checkout','staging','module','checkout_flow','present');
INSERT INTO "env_state" VALUES('checkout','production','module','checkout_flow','present');
INSERT INTO "env_state" VALUES('payments','staging','config','notifications_retry_max_attempts','0');
INSERT INTO "env_state" VALUES('payments','production','config','notifications_retry_max_attempts','0');
INSERT INTO "env_state" VALUES('payments','staging','config','notifications_timeout_ms','30000');
INSERT INTO "env_state" VALUES('payments','production','config','notifications_timeout_ms','30000');
INSERT INTO "env_state" VALUES('payments','staging','config','db_pool_size','20');
INSERT INTO "env_state" VALUES('payments','production','config','db_pool_size','20');
INSERT INTO "env_state" VALUES('payments','staging','dependency','libpayproc','2.3.1');
INSERT INTO "env_state" VALUES('payments','production','dependency','libpayproc','2.3.1');
INSERT INTO "env_state" VALUES('payments','staging','dependency','requests','2.32.3');
INSERT INTO "env_state" VALUES('payments','production','dependency','requests','2.32.3');
INSERT INTO "env_state" VALUES('payments','staging','module','payment_capture','present');
INSERT INTO "env_state" VALUES('payments','production','module','payment_capture','present');
INSERT INTO "env_state" VALUES('payments','staging','module','refund_flow','present');
INSERT INTO "env_state" VALUES('payments','production','module','refund_flow','present');
INSERT INTO "env_state" VALUES('notifications','staging','config','smtp_pool','8');
INSERT INTO "env_state" VALUES('notifications','production','config','smtp_pool','8');
INSERT INTO "env_state" VALUES('search','staging','config','cache_enabled','false');
INSERT INTO "env_state" VALUES('search','production','config','cache_enabled','false');
INSERT INTO "env_state" VALUES('search','staging','config','cache_ttl_s','300');
INSERT INTO "env_state" VALUES('search','production','config','cache_ttl_s','300');
INSERT INTO "env_state" VALUES('search','staging','config','index_shards','4');
INSERT INTO "env_state" VALUES('search','production','config','index_shards','4');
INSERT INTO "env_state" VALUES('storefront-web','staging','version','current','v3.2.4');
INSERT INTO "env_state" VALUES('storefront-web','production','version','current','v3.2.4');
INSERT INTO "env_state" VALUES('api-gateway','staging','version','current','v5.1.0');
INSERT INTO "env_state" VALUES('api-gateway','production','version','current','v5.1.0');
INSERT INTO "env_state" VALUES('catalog','staging','version','current','v1.9.2');
INSERT INTO "env_state" VALUES('catalog','production','version','current','v1.9.2');
INSERT INTO "env_state" VALUES('checkout','staging','version','current','v2.6.3');
INSERT INTO "env_state" VALUES('checkout','production','version','current','v2.6.3');
INSERT INTO "env_state" VALUES('payments','staging','version','current','v2.7.0');
INSERT INTO "env_state" VALUES('payments','production','version','current','v2.7.0');
INSERT INTO "env_state" VALUES('notifications','staging','version','current','v1.4.8');
INSERT INTO "env_state" VALUES('notifications','production','version','current','v1.4.8');
INSERT INTO "env_state" VALUES('search','staging','version','current','v3.0.5');
INSERT INTO "env_state" VALUES('search','production','version','current','v3.0.5');
INSERT INTO "env_state" VALUES('api-gateway','production','traffic','/v1/orders','100');
INSERT INTO "env_state" VALUES('api-gateway','production','traffic','/v2/orders','0');
INSERT INTO "env_state" VALUES('api-gateway','production','traffic','/v1/checkout','100');
INSERT INTO "env_state" VALUES('api-gateway','production','traffic','/internal/debug','0');
INSERT INTO "feature_flags" VALUES(9301,'instant_refunds','checkout','Pilot: refund immediately at checkout instead of async batch.','production',1,100);
INSERT INTO "feature_flags" VALUES(9302,'instant_refunds','checkout','Pilot: refund immediately at checkout instead of async batch.','staging',1,100);
INSERT INTO "feature_flags" VALUES(9303,'new_search_ui','search','Redesigned search results page.','production',0,0);
INSERT INTO "feature_flags" VALUES(9304,'new_search_ui','search','Redesigned search results page.','staging',1,100);
INSERT INTO "incidents" VALUES(9701,'sev1','API gateway latency surge after v5.1.0 rollout','api-gateway','open','');
INSERT INTO "incidents" VALUES(9702,'sev2','Checkout error spike since instant_refunds ramp','checkout','open','');
INSERT INTO "logs" VALUES(9010,'payments','production','ERROR','ConnectionTimeout calling notifications after 30000ms - request failed permanently (retry_max_attempts=0, no retry attempted); order marked failed');
INSERT INTO "logs" VALUES(9011,'payments','production','ERROR','ConnectionTimeout calling notifications after 30000ms - request failed permanently (retry_max_attempts=0, no retry attempted); order marked failed');
INSERT INTO "logs" VALUES(9012,'payments','production','INFO','startup config: notifications_retry_max_attempts=0 notifications_timeout_ms=30000 db_pool_size=20');
INSERT INTO "logs" VALUES(9013,'search','production','WARN','query cache disabled (cache_enabled=false); every request is hitting the primary index');
INSERT INTO "logs" VALUES(9014,'api-gateway','production','ERROR','p99 latency 1030ms; regression began immediately after deploy v5.1.0 (suspected goroutine leak in upstream connection pool)');
INSERT INTO "logs" VALUES(9015,'checkout','production','ERROR','refund worker panic: nil pointer in instant_refunds path; errors correlate 1:1 with feature flag instant_refunds=enabled');
INSERT INTO "logs" VALUES(9016,'checkout','production','WARN','CI: test_checkout_idempotency failed on run #142, passed on rerun #143 - nondeterministic idempotency-key collision in test fixture');
INSERT INTO "logs" VALUES(9017,'notifications','production','INFO','delivery queue healthy; smtp_pool=8');
INSERT INTO "messages" VALUES(1,'#incidents','Priya Nair','Declared incident 9701 (sev1): api-gateway p99 through the roof since the v5.1.0 promote.');
INSERT INTO "messages" VALUES(2,'#incidents','Diego Ramos','Incident 9702 (sev2): checkout error rate tracks the instant_refunds ramp exactly.');
INSERT INTO "messages" VALUES(3,'#eng','Mei Tanaka','Reminder: deployment policy = staging first; tier-1 canary at 25% then promote.');
INSERT INTO "metric_rules" VALUES(9401,'payments','error_rate_pct','base','','',0.4);
INSERT INTO "metric_rules" VALUES(9402,'payments','error_rate_pct','config_eq','notifications_retry_max_attempts','0',3.8);
INSERT INTO "metric_rules" VALUES(9403,'search','latency_p99_ms','base','','',210.0);
INSERT INTO "metric_rules" VALUES(9404,'search','latency_p99_ms','config_eq','cache_enabled','false',640.0);
INSERT INTO "metric_rules" VALUES(9405,'checkout','error_rate_pct','base','','',0.3);
INSERT INTO "metric_rules" VALUES(9406,'checkout','error_rate_pct','flag_enabled','instant_refunds','',5.2);
INSERT INTO "metric_rules" VALUES(9407,'api-gateway','latency_p99_ms','base','','',120.0);
INSERT INTO "metric_rules" VALUES(9408,'api-gateway','latency_p99_ms','version_ge','','v5.1.0',910.0);
INSERT INTO "metric_rules" VALUES(9409,'payments','latency_p99_ms','base','','',95.0);
INSERT INTO "metric_rules" VALUES(9410,'checkout','latency_p99_ms','base','','',180.0);
INSERT INTO "metric_rules" VALUES(9411,'api-gateway','error_rate_pct','base','','',0.2);
INSERT INTO "metric_rules" VALUES(9412,'search','error_rate_pct','base','','',0.1);
INSERT INTO "oncall" VALUES('platform','Priya Nair');
INSERT INTO "oncall" VALUES('commerce','Diego Ramos');
INSERT INTO "oncall" VALUES('growth','Mei Tanaka');
INSERT INTO "oncall" VALUES('sre','Alex Osei');
INSERT INTO "pull_requests" VALUES(9201,'api-gateway','Connection pool rewrite','Perf: new upstream pool.','Priya Nair','','merged','v5.1.0');
INSERT INTO "pull_requests" VALUES(9202,'catalog','Price rounding cleanup','Draft, do not merge yet.','Diego Ramos','','open','');
INSERT INTO "repo_state" VALUES('storefront-web','config','ab_test_bucket','b');
INSERT INTO "repo_state" VALUES('storefront-web','module','homepage','present');
INSERT INTO "repo_state" VALUES('storefront-web','module','product_page','present');
INSERT INTO "repo_state" VALUES('api-gateway','config','rate_limit_rps','500');
INSERT INTO "repo_state" VALUES('api-gateway','endpoint','/v1/orders','active');
INSERT INTO "repo_state" VALUES('api-gateway','endpoint','/v2/orders','active');
INSERT INTO "repo_state" VALUES('api-gateway','endpoint','/v1/checkout','active');
INSERT INTO "repo_state" VALUES('api-gateway','endpoint','/internal/debug','active');
INSERT INTO "repo_state" VALUES('catalog','config','cdn_enabled','true');
INSERT INTO "repo_state" VALUES('catalog','module','product_listing','present');
INSERT INTO "repo_state" VALUES('checkout','config','payment_timeout_ms','8000');
INSERT INTO "repo_state" VALUES('checkout','dependency','stripe-sdk','11.2.0');
INSERT INTO "repo_state" VALUES('checkout','module','cart','present');
INSERT INTO "repo_state" VALUES('checkout','module','checkout_flow','present');
INSERT INTO "repo_state" VALUES('payments','config','notifications_retry_max_attempts','0');
INSERT INTO "repo_state" VALUES('payments','config','notifications_timeout_ms','30000');
INSERT INTO "repo_state" VALUES('payments','config','db_pool_size','20');
INSERT INTO "repo_state" VALUES('payments','dependency','libpayproc','2.3.1');
INSERT INTO "repo_state" VALUES('payments','dependency','requests','2.32.3');
INSERT INTO "repo_state" VALUES('payments','module','payment_capture','present');
INSERT INTO "repo_state" VALUES('payments','module','refund_flow','present');
INSERT INTO "repo_state" VALUES('notifications','config','smtp_pool','8');
INSERT INTO "repo_state" VALUES('search','config','cache_enabled','false');
INSERT INTO "repo_state" VALUES('search','config','cache_ttl_s','300');
INSERT INTO "repo_state" VALUES('search','config','index_shards','4');
INSERT INTO "runbooks" VALUES(9951,'Retry policy standard','All cross-service calls MUST configure retries: set config key ''<downstream>_retry_max_attempts'' to 3 (exponential backoff is applied automatically). A value of 0 means a single downstream timeout permanently fails the request.');
INSERT INTO "runbooks" VALUES(9952,'Deployment policy','Every production deploy must first succeed on staging (same version). Tier-1 services (storefront-web, api-gateway, checkout, payments) must additionally canary in production at <=25% (deploy_service with canary_percent<=25) and promote with promote_canary only after verification. Use rollback_deployment for emergency rollback; rollbacks are exempt from the staging-first rule.');
INSERT INTO "runbooks" VALUES(9953,'Search caching','cache_enabled=true is required in production for the search service; the query cache absorbs ~75% of index load. TTL standard is 300s.');
INSERT INTO "runbooks" VALUES(9954,'Incident response','1) acknowledge the firing alert 2) mitigate (rollback or feature-flag kill switch) 3) verify metric recovery 4) resolve the alert 5) resolve the incident 6) post an update in #incidents 7) for sev1: file a postmortem ticket (type ''postmortem'').');
INSERT INTO "runbooks" VALUES(9955,'API deprecation','Deprecate the endpoint first (status ''deprecated'') and deploy that change. Then shift traffic to the replacement in stages of at most 50 percentage points per step. Only when the legacy endpoint serves 0% traffic may it be retired (status ''retired''); CI blocks retirement of endpoints still serving traffic.');
INSERT INTO "runbooks" VALUES(9956,'Security response','Patch the vulnerable dependency, deploy staging then production, verify the scanner shows the finding remediated, post an audit summary to #security referencing the CVE id, and close the security ticket.');
INSERT INTO "runbooks" VALUES(9957,'Feature flags','New user-facing features ship dark behind a flag (define the flag via a ''flag'' PR change; it is created disabled in both environments at merge). The guarded code must be deployed to production BEFORE the flag is enabled there. Initial production rollout must not exceed 10%. Flags are runtime toggles: set_feature_flag needs no deploy.');
INSERT INTO "runbooks" VALUES(9958,'Flaky tests','Diagnose from CI history (list_ci_runs). Fix the root cause via a PR with a test_fix change (action ''fix''); quarantine (action ''quarantine'') is a last resort and does not close the ticket. After merging, prove stability with 3 consecutive green main-branch runs: run_ci(service=...).');
INSERT INTO "service_metrics" VALUES('payments','production','error_rate_pct',4.2);
INSERT INTO "service_metrics" VALUES('search','production','latency_p99_ms',850.0);
INSERT INTO "service_metrics" VALUES('checkout','production','error_rate_pct',5.5);
INSERT INTO "service_metrics" VALUES('api-gateway','production','latency_p99_ms',1030.0);
INSERT INTO "service_metrics" VALUES('payments','production','latency_p99_ms',95.0);
INSERT INTO "service_metrics" VALUES('checkout','production','latency_p99_ms',180.0);
INSERT INTO "service_metrics" VALUES('api-gateway','production','error_rate_pct',0.2);
INSERT INTO "service_metrics" VALUES('search','production','error_rate_pct',0.1);
INSERT INTO "services" VALUES(9001,'storefront-web','growth',1,'typescript','Customer-facing web storefront (Next.js).','v3.2.4');
INSERT INTO "services" VALUES(9002,'api-gateway','platform',1,'go','Public API edge: routing, auth, rate limiting, traffic weighting.','v5.1.0');
INSERT INTO "services" VALUES(9003,'catalog','commerce',2,'python','Product catalog and pricing service.','v1.9.2');
INSERT INTO "services" VALUES(9004,'checkout','commerce',1,'python','Cart and checkout orchestration.','v2.6.3');
INSERT INTO "services" VALUES(9005,'payments','commerce',1,'python','Payment capture, refunds, and settlement.','v2.7.0');
INSERT INTO "services" VALUES(9006,'notifications','platform',2,'python','Email/SMS/push notification delivery.','v1.4.8');
INSERT INTO "services" VALUES(9007,'search','growth',2,'python','Product search and ranking.','v3.0.5');
INSERT INTO "slos" VALUES(9501,'payments','error_rate_pct',1.0,'Payments requests must succeed 99% of the time.');
INSERT INTO "slos" VALUES(9502,'search','latency_p99_ms',300.0,'Search p99 latency under 300ms.');
INSERT INTO "slos" VALUES(9503,'checkout','error_rate_pct',1.0,'Checkout requests must succeed 99% of the time.');
INSERT INTO "slos" VALUES(9504,'api-gateway','latency_p99_ms',250.0,'Gateway p99 latency under 250ms.');
INSERT INTO "slos" VALUES(9505,'payments','latency_p99_ms',200.0,'Payments p99 latency under 200ms.');
INSERT INTO "slos" VALUES(9506,'checkout','latency_p99_ms',400.0,'Checkout p99 latency under 400ms.');
INSERT INTO "tests_catalog" VALUES(9901,'checkout','unit','test_cart_totals','passing',0);
INSERT INTO "tests_catalog" VALUES(9902,'checkout','integration','test_checkout_idempotency','flaky',0);
INSERT INTO "tests_catalog" VALUES(9903,'payments','unit','test_capture_retries','passing',0);
INSERT INTO "tests_catalog" VALUES(9904,'search','unit','test_ranking','passing',0);
INSERT INTO "tickets" VALUES(9101,'ENG-2101','bug','Reduce payments error rate breaching SLO','payments error_rate_pct has been breaching its 1.0% SLO for two days (alert 9601). Investigate production logs to find the root cause, fix it through the standard PR -> CI -> merge -> staged deployment workflow (see the ''Deployment policy'' runbook: staging first, tier-1 services canary at <=25% then promote), confirm the metric recovered, resolve the alert, and close this ticket.','open','high','','payments');
INSERT INTO "tickets" VALUES(9102,'ENG-2102','bug','Search p99 latency exceeds SLO','search latency_p99_ms is 850ms against a 300ms SLO (alert 9602). Find the root cause (see logs and the ''Search caching'' runbook), ship the fix staging-first, confirm recovery, resolve the alert, and close this ticket.','open','high','','search');
INSERT INTO "tickets" VALUES(9103,'ENG-2201','feature','Ship express checkout behind a feature flag at 10% production rollout','Implement the express_checkout module in the checkout service gated behind a NEW feature flag named ''express_checkout'' (define the flag in the same PR with a ''flag'' change). Per the ''Feature flags'' runbook the code must be deployed to production (staging first, canary then promote — checkout is tier 1) BEFORE the flag is enabled. Then enable the flag in production at a 10% rollout. Close this ticket when done.','open','medium','','checkout');
INSERT INTO "tickets" VALUES(9104,'ENG-2202','incident','Disable instant_refunds and resolve checkout error spike','Incident 9702 (sev2): checkout error_rate_pct jumped to 5.5% right after the instant_refunds flag ramped to 100% in production. Per the ''Incident response'' runbook: acknowledge the alert, kill-switch the flag in production (leave staging as-is), verify the metric recovered, resolve the alert and the incident, post an update in #incidents mentioning instant_refunds, and close this ticket.','open','critical','','checkout');
INSERT INTO "tickets" VALUES(9105,'SEC-901','security','Patch CVE-2026-31337 in libpayproc (payments)','Security scanner reports libpayproc 2.3.1 in payments is vulnerable to CVE-2026-31337 (critical). Upgrade the dependency to the fixed version 2.4.0 via the standard workflow, deploy staging-first (payments is tier 1: canary then promote), confirm the scanner shows the vulnerability remediated, post an audit summary to #security referencing the CVE, and close this ticket.','open','critical','','payments');
INSERT INTO "tickets" VALUES(9106,'SEC-902','security','Retire exposed /internal/debug endpoint on api-gateway','A security review found the unauthenticated /internal/debug endpoint still active in production on api-gateway. Retire it via an endpoint PR change and deploy staging-first (api-gateway is tier 1: canary then promote). Close this ticket.','open','high','','api-gateway');
INSERT INTO "tickets" VALUES(9107,'ENG-2301','feature','Loyalty points across catalog, checkout, and storefront-web','Ship the loyalty-points feature: add module ''loyalty_accrual'' to catalog, module ''loyalty_redeem'' to checkout, and module ''loyalty_widget'' to storefront-web (one PR per service). Deployment order matters: catalog must reach production before checkout, and checkout before storefront-web. Every production deploy is staging-first; checkout and storefront-web are tier 1 (canary <=25% then promote). Close this ticket when all three are live.','open','medium','','');
INSERT INTO "tickets" VALUES(9108,'ENG-2302','feature','Migrate /v1/orders traffic to /v2/orders and retire v1','Per the ''API deprecation'' runbook: mark /v1/orders deprecated (endpoint PR change) and deploy that to production first; then shift traffic from /v1/orders to /v2/orders in stages of at most 50 percentage points per step until /v2/orders serves 100% and /v1/orders serves 0%; only then retire /v1/orders with a second PR and deploy it. api-gateway is tier 1 (staging first, canary then promote). Close this ticket when v1 is retired in production.','open','medium','','api-gateway');
INSERT INTO "tickets" VALUES(9109,'ENG-2401','bug','Fix flaky test_checkout_idempotency; prove 3 consecutive green main runs','checkout CI is unreliable: test_checkout_idempotency fails intermittently (see CI history). Fix the root cause via a PR with a test_fix change (action ''fix'' — do NOT just quarantine it), merge it, then demonstrate stability with at least 3 consecutive green main-branch CI runs (run_ci with service=''checkout''). Close this ticket.','open','high','','checkout');
INSERT INTO "tickets" VALUES(9110,'ENG-2402','incident','SEV1: roll back api-gateway v5.1.0 and file postmortem','Incident 9701 (sev1): api-gateway p99 latency jumped to ~1030ms right after v5.1.0 was promoted in production. Per the ''Incident response'' runbook: acknowledge the alert, roll back the production deployment, verify the metric recovered, resolve the alert and the incident, create a postmortem ticket (type ''postmortem'', service api-gateway, mention v5.1.0), post an update in #incidents, and close this ticket.','open','critical','','api-gateway');
INSERT INTO "versions" VALUES(1,'storefront-web','v3.2.4','[["config", "ab_test_bucket", "b"], ["module", "homepage", "present"], ["module", "product_page", "present"]]');
INSERT INTO "versions" VALUES(2,'api-gateway','v5.1.0','[["config", "rate_limit_rps", "500"], ["endpoint", "/internal/debug", "active"], ["endpoint", "/v1/checkout", "active"], ["endpoint", "/v1/orders", "active"], ["endpoint", "/v2/orders", "active"]]');
INSERT INTO "versions" VALUES(3,'catalog','v1.9.2','[["config", "cdn_enabled", "true"], ["module", "product_listing", "present"]]');
INSERT INTO "versions" VALUES(4,'checkout','v2.6.3','[["config", "payment_timeout_ms", "8000"], ["dependency", "stripe-sdk", "11.2.0"], ["module", "cart", "present"], ["module", "checkout_flow", "present"]]');
INSERT INTO "versions" VALUES(5,'payments','v2.7.0','[["config", "db_pool_size", "20"], ["config", "notifications_retry_max_attempts", "0"], ["config", "notifications_timeout_ms", "30000"], ["dependency", "libpayproc", "2.3.1"], ["dependency", "requests", "2.32.3"], ["module", "payment_capture", "present"], ["module", "refund_flow", "present"]]');
INSERT INTO "versions" VALUES(6,'notifications','v1.4.8','[["config", "smtp_pool", "8"]]');
INSERT INTO "versions" VALUES(7,'search','v3.0.5','[["config", "cache_enabled", "false"], ["config", "cache_ttl_s", "300"], ["config", "index_shards", "4"]]');
INSERT INTO "versions" VALUES(8,'api-gateway','v5.0.9','[["config", "rate_limit_rps", "500"], ["endpoint", "/internal/debug", "active"], ["endpoint", "/v1/checkout", "active"], ["endpoint", "/v1/orders", "active"], ["endpoint", "/v2/orders", "active"]]');
INSERT INTO "vulnerabilities" VALUES(9801,'CVE-2026-31337','libpayproc','payments','critical','2.4.0','open');
INSERT INTO "sqlite_sequence" VALUES('tickets',9110);
INSERT INTO "sqlite_sequence" VALUES('ci_runs',4);
INSERT INTO "sqlite_sequence" VALUES('deployments',9266);
INSERT INTO "sqlite_sequence" VALUES('feature_flags',9304);
INSERT INTO "sqlite_sequence" VALUES('alerts',9604);
INSERT INTO "sqlite_sequence" VALUES('incidents',9702);
INSERT INTO "sqlite_sequence" VALUES('messages',3);
INSERT INTO "sqlite_sequence" VALUES('versions',8);
INSERT INTO "sqlite_sequence" VALUES('audit_events',17);
